import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

// Minimal globals we need — avoids pulling the `globals` npm package.
const nodeGlobals = {
  process: 'readonly',
  console: 'readonly',
  Buffer: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  global: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  setImmediate: 'readonly',
  clearImmediate: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
};
const browserGlobals = {
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  location: 'readonly',
  localStorage: 'readonly',
};

export default [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': ['error', { allow: ['info', 'warn', 'error'] }],
    },
  },
  // Package boundary enforce — código fuera de packages/* y fuera de los
  // archivos owner originales debe consumir las facades `@npricing/*`, no
  // los implementation paths. Complementa el test custom de
  // utils/__tests__/packageBoundaryImports.test.ts; el test es la verdad
  // canónica (cubre más rutas y permite excepciones explícitas), esta regla
  // se queda como guardia rápida y feedback en IDE para los offenders más
  // comunes (pricingEngine, canonicalJson, snapshotHash).
  {
    files: ['**/*.ts', '**/*.tsx'],
    ignores: [
      'packages/**',
      'utils/pricingEngine.ts',
      'utils/canonicalJson.ts',
      'utils/snapshotHash.ts',
      'utils/governance/dossierSigning.ts',
      'utils/pricing/**',
      '**/__tests__/**',
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.stories.tsx',
      'utils/channels/**',
      'utils/clv/**',
      'utils/customer360/**',
      'utils/targetGrid/**',
      'utils/governance/**',
      'utils/backtesting/**',
    ],
    rules: {
      'no-restricted-imports': ['warn', {
        patterns: [
          {
            group: ['**/pricingEngine', '**/utils/pricingEngine'],
            message: 'Importa desde @npricing/pricing-core en vez de utils/pricingEngine directamente.',
          },
          {
            group: ['**/canonicalJson', '**/snapshotHash'],
            message: 'Importa desde @npricing/evidence en vez de utils/canonicalJson o utils/snapshotHash.',
          },
        ],
      }],
    },
  },
  // Node-only scripts (Playwright callbacks execute in browser context, so we
  // also expose browser globals — ESLint cannot statically distinguish between
  // the script scope and `page.evaluate(() => {...})` callbacks).
  {
    files: ['scripts/**/*.{js,mjs,ts}', 'supabase/functions/**/*.mjs'],
    languageOptions: {
      globals: { ...nodeGlobals, ...browserGlobals },
    },
    rules: {
      'no-console': 'off',
    },
  },
  // Server runtime
  {
    files: ['server/**/*.ts'],
    languageOptions: { globals: nodeGlobals },
  },
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'playwright-report/**',
      'storybook-static/**',
      'test-results/**',
      // Generated by `npm run build:edge` before edge typecheck — bundled pricing engine, not hand-written source.
      'supabase/functions/pricing/pricingBundle.js',
      'supabase/functions/pricing/pricingBundle.js.map',
    ],
  },
];
