/**
 * Pricing Copilot — explains why the EV-optimal recommended rate differs
 * from the commercial margin target.
 *
 * See: docs/pivot/ai-assistant-refocus.md §2
 */

import { invokeAI } from './client';

const SYSTEM_PROMPT = `You are the N-Pricing Copilot. You help bank originators
understand pricing recommendations generated by the N-Pricing engine.

YOUR JOB:
1. Explain in plain language (Spanish by default, English if prompted in English)
   why the recommended rate is X bp away from the proposed rate.
2. Attribute the delta to specific drivers (elasticity signal, capital charge,
   ESG adjustment, liquidity premium) — cite the breakdown numbers verbatim.
3. If the proposed rate would result in significantly lower EV, say so clearly.
4. If the elasticity model confidence is LOW or MEDIUM, flag it explicitly.
5. Do NOT invent numbers. Only cite what is provided in the CONTEXT block.
6. Keep response under 150 words unless user asks for detail.

FORMAT (strict):
- One-sentence verdict (e.g., "Your rate of 4.35% is 17bp above the EV-optimal.")
- 2-4 bullets with driver attribution.
- Final line: confidence qualifier.

REFUSE to give investment advice, credit decisions, or legal guidance.
If asked about non-pricing topics, redirect to the appropriate N-Pricing view.`;

export interface PricingCopilotContext {
  proposedRate: number;            // % e.g. 4.35
  recommendedRate: number;          // % e.g. 4.18
  pWinProposed: number;             // 0-1
  pWinRecommended: number;          // 0-1
  ftpBreakdown: {
    baseRate: number;
    liquidityPremium: number;
    capitalCharge: number;
    esgAdjustmentBp: number;
    regulatoryCost: number;
  };
  segment: string;
  elasticityConfidence: 'LOW' | 'MEDIUM' | 'HIGH';
  sampleSize: number;
  currency?: string;
  amount?: number;
  language?: 'es' | 'en';
}

export interface PricingCopilotResult {
  ok: true;
  explanation: string;
  latencyMs: number;
}

export interface PricingCopilotFailure {
  ok: false;
  reason: 'AI_UNAVAILABLE' | 'EMPTY_RESPONSE';
}

export const buildPricingCopilotPrompt = (ctx: PricingCopilotContext): string => {
  const lang = ctx.language ?? 'es';
  const deltaBp = Math.round((ctx.proposedRate - ctx.recommendedRate) * 100);
  const ftp = ctx.ftpBreakdown;
  const pWinLoss = Math.round((ctx.pWinRecommended - ctx.pWinProposed) * 100);
  return `CONTEXT:
- Segment: ${ctx.segment}
- Amount: ${ctx.amount ?? '?'} ${ctx.currency ?? ''}
- Proposed rate: ${ctx.proposedRate.toFixed(2)}%
- Recommended rate: ${ctx.recommendedRate.toFixed(2)}%
- Delta proposed - recommended: ${deltaBp}bp
- P(win) at proposed: ${(ctx.pWinProposed * 100).toFixed(0)}%
- P(win) at recommended: ${(ctx.pWinRecommended * 100).toFixed(0)}%
- P(win) swing: ${pWinLoss > 0 ? '+' : ''}${pWinLoss}pp

FTP BREAKDOWN:
- Base rate: ${ftp.baseRate.toFixed(3)}%
- Liquidity premium: ${ftp.liquidityPremium.toFixed(3)}%
- Capital charge: ${ftp.capitalCharge.toFixed(3)}%
- ESG adjustment: ${ftp.esgAdjustmentBp}bp
- Regulatory cost (ECL): ${(ftp.regulatoryCost * 100).toFixed(3)}%

ELASTICITY MODEL:
- Confidence: ${ctx.elasticityConfidence}
- Sample size: ${ctx.sampleSize}

Respond in ${lang === 'es' ? 'Spanish' : 'English'}.`;
};

export async function explainPricingRecommendation(
  ctx: PricingCopilotContext,
  signal?: AbortSignal,
): Promise<PricingCopilotResult | PricingCopilotFailure> {
  const result = await invokeAI({
    capability: 'PRICING_COPILOT',
    systemPrompt: SYSTEM_PROMPT,
    userMessage: buildPricingCopilotPrompt(ctx),
    temperature: 0.3,
    signal,
  });

  if (result.outcome !== 'SUCCESS') {
    return { ok: false, reason: 'AI_UNAVAILABLE' };
  }

  const text = result.text.trim();
  if (!text) {
    return { ok: false, reason: 'EMPTY_RESPONSE' };
  }

  return { ok: true, explanation: text, latencyMs: result.latencyMs };
}
