/**
 * Mock deals catalogue — seed/fallback data for offline mode and tests.
 *
 * Extracted from `utils/seedData.ts` (2026-05-14) to reduce that file
 * below 1k lines and group deals as their own concern. Consumers continue
 * importing from `utils/seedData` (barrel re-export) — no API change.
 */

import type { Transaction } from '../types';

export const MOCK_DEALS: Transaction[] = [
  {
    id: 'TRD-HYPER-001',
    clientId: 'CL-1001',
    clientType: 'Corporate',
    productType: 'LOAN_COMM',
    category: 'Asset',
    amount: 25000000,
    currency: 'USD',
    marginTarget: 1.75,
    startDate: '2023-11-01',
    status: 'Booked',
    businessLine: 'Corporate',
    businessUnit: 'BU-001',
    fundingBusinessUnit: 'BU-900',
    durationMonths: 60,
    amortization: 'French',
    repricingFreq: 'Monthly',
    riskWeight: 100,
    capitalRatio: 12.0,
    targetROE: 15,
    operationalCostBps: 35,
    lcrOutflowPct: 0,
    transitionRisk: 'Neutral',
    physicalRisk: 'Low',
    description: 'Crédito Corporativo Estándar - 5Y',
  },
  {
    id: 'TRD-HYPER-002',
    clientId: 'CL-4099',
    clientType: 'Retail',
    productType: 'LOAN_MORT',
    category: 'Asset',
    amount: 350000,
    currency: 'EUR',
    marginTarget: 1.2,
    startDate: '2023-10-15',
    status: 'Booked',
    businessLine: 'Retail',
    businessUnit: 'BU-002',
    fundingBusinessUnit: 'BU-900',
    durationMonths: 240,
    amortization: 'French',
    repricingFreq: 'Fixed',
    riskWeight: 35,
    capitalRatio: 11.5,
    targetROE: 12,
    operationalCostBps: 20,
    lcrOutflowPct: 0,
    transitionRisk: 'Green',
    physicalRisk: 'Medium',
    description: 'Hipoteca Residencial Eficiente (ESG Premium)',
  },
  {
    id: 'TRD-HYPER-003',
    clientId: 'CL-1002',
    clientType: 'Corporate',
    productType: 'DEP_TERM',
    category: 'Liability',
    amount: 15000000,
    currency: 'USD',
    marginTarget: 0.85,
    startDate: '2023-11-20',
    status: 'Booked',
    businessLine: 'Corporate',
    businessUnit: 'BU-001',
    fundingBusinessUnit: 'BU-900',
    durationMonths: 12,
    amortization: 'Bullet',
    repricingFreq: 'Fixed',
    riskWeight: 0,
    capitalRatio: 12.0,
    targetROE: 10,
    operationalCostBps: 10,
    lcrOutflowPct: 25,
    isOperationalSegment: true,
    transitionRisk: 'Neutral',
    physicalRisk: 'Low',
    description: 'Depósito Operativo - Mitigación LCR',
  },
  {
    id: 'TRD-HYPER-004',
    clientId: 'CL-3055',
    clientType: 'Institution',
    productType: 'CRED_LINE',
    category: 'Off-Balance',
    amount: 50000000,
    currency: 'EUR',
    marginTarget: 0.45,
    startDate: '2023-11-10',
    status: 'Pending',
    businessLine: 'Institutional',
    businessUnit: 'BU-001',
    fundingBusinessUnit: 'BU-900',
    durationMonths: 36,
    amortization: 'Bullet',
    repricingFreq: 'Daily',
    riskWeight: 100,
    capitalRatio: 11.5,
    targetROE: 14,
    operationalCostBps: 15,
    lcrOutflowPct: 40,
    undrawnAmount: 45000000,
    isCommitted: true,
    transitionRisk: 'Neutral',
    physicalRisk: 'Low',
    description: 'Línea de Crédito Comprometida - Impacto CLC',
  },
  {
    id: 'TRD-HYPER-005',
    clientId: 'CL-2001',
    clientType: 'SME',
    productType: 'LOAN_COMM',
    category: 'Asset',
    amount: 1200000,
    currency: 'USD',
    marginTarget: 3.5,
    startDate: '2023-11-25',
    status: 'Review',
    businessLine: 'SME',
    businessUnit: 'BU-003',
    fundingBusinessUnit: 'BU-900',
    durationMonths: 48,
    amortization: 'Linear',
    repricingFreq: 'Quarterly',
    riskWeight: 100,
    capitalRatio: 12.0,
    targetROE: 18,
    operationalCostBps: 85,
    lcrOutflowPct: 0,
    transitionRisk: 'Amber',
    physicalRisk: 'High',
    description: 'Préstamo SME - Riesgo de Transición Sectorial',
  },
  {
    id: 'TRD-HYPER-006',
    clientId: 'CL-3055',
    clientType: 'Institution',
    productType: 'DEP_CASA',
    category: 'Liability',
    amount: 100000000,
    currency: 'USD',
    marginTarget: 0.1,
    startDate: '2023-11-01',
    status: 'Booked',
    businessLine: 'Treasury',
    businessUnit: 'BU-900',
    fundingBusinessUnit: 'BU-900',
    durationMonths: 1,
    amortization: 'Bullet',
    repricingFreq: 'Daily',
    riskWeight: 0,
    capitalRatio: 11.5,
    targetROE: 12,
    operationalCostBps: 5,
    lcrOutflowPct: 100,
    isOperationalSegment: false,
    transitionRisk: 'Neutral',
    physicalRisk: 'Low',
    description: 'Fondeo Mayorista (Financial Inst.) - 100% LCR Outflow',
  },
  {
    id: 'DL-DEMO-001',
    clientId: 'CL-1001',
    clientType: 'Corporate',
    productType: 'LOAN_COMM',
    category: 'Asset',
    amount: 10000000,
    currency: 'USD',
    marginTarget: 2.5,
    startDate: '2024-01-01',
    status: 'Review',
    businessLine: 'Demo',
    businessUnit: 'BU-001',
    fundingBusinessUnit: 'BU-900',
    durationMonths: 6,
    amortization: 'Bullet',
    repricingFreq: 'Fixed',
    riskWeight: 100,
    capitalRatio: 12.0,
    targetROE: 15,
    operationalCostBps: 45,
    transitionRisk: 'Neutral',
    physicalRisk: 'Low',
    description: 'Gatillo NSFR: Activo < 12M forzando suelo 1Y.',
  },
  {
    id: 'DL-DEMO-002',
    clientId: 'CL-1002',
    clientType: 'Corporate',
    productType: 'DEP_TERM',
    category: 'Liability',
    amount: 50000000,
    currency: 'USD',
    marginTarget: 1.2,
    startDate: '2024-01-01',
    status: 'Booked',
    businessLine: 'Demo',
    businessUnit: 'BU-001',
    fundingBusinessUnit: 'BU-900',
    durationMonths: 12,
    amortization: 'Bullet',
    repricingFreq: 'Fixed',
    riskWeight: 0,
    capitalRatio: 11.5,
    targetROE: 12,
    operationalCostBps: 15,
    lcrOutflowPct: 25,
    isOperationalSegment: true,
    transitionRisk: 'Neutral',
    physicalRisk: 'Low',
    description: 'LCR/Op Split: Beneficio depósito operativo.',
  },
  {
    id: 'DL-DEMO-004',
    clientId: 'CL-1001',
    clientType: 'Corporate',
    productType: 'CRED_LINE',
    category: 'Off-Balance',
    amount: 100000000,
    currency: 'USD',
    marginTarget: 0.5,
    startDate: '2024-01-01',
    status: 'Pending',
    businessLine: 'Demo',
    businessUnit: 'BU-001',
    fundingBusinessUnit: 'BU-900',
    durationMonths: 36,
    amortization: 'Bullet',
    repricingFreq: 'Daily',
    riskWeight: 75,
    capitalRatio: 11.5,
    targetROE: 14,
    operationalCostBps: 20,
    lcrOutflowPct: 10,
    undrawnAmount: 85000000,
    isCommitted: true,
    transitionRisk: 'Neutral',
    physicalRisk: 'Low',
    description: 'CLC Masivo: Impacto línea comprometida no dispuesta.',
  },
  {
    id: 'TRD-IRS-001',
    clientId: 'CL-3055',
    clientType: 'Institution',
    productType: 'SWAP_IRS',
    category: 'Off-Balance',
    amount: 25000000,
    currency: 'EUR',
    marginTarget: 0.15,
    startDate: '2023-12-01',
    status: 'Review',
    businessLine: 'Derivatives',
    businessUnit: 'BU-001',
    fundingBusinessUnit: 'BU-900',
    durationMonths: 120,
    amortization: 'Bullet',
    repricingFreq: 'Monthly',
    riskWeight: 20,
    capitalRatio: 12.0,
    targetROE: 15,
    operationalCostBps: 10,
    transitionRisk: 'Neutral',
    physicalRisk: 'Low',
    description: 'IRS Swap - Cobertura de Tipo de Interés',
  },
];
